/**
 * Created by יאיר on 18/01/2017.
 */
lmdd.init(document.getElementById('simple-example'),{
    containerClass:'nestable',
    fixedItemClass:false,
    draggableItemClass:'item',
    handleClass:false,
    regulateMouseOver:false,
    mirrorMaxHeight:100,
    mirrorMaxWidth:300,
    revert:false,
    clone:false
});
lmdd.init(document.getElementById('simple-example-2'),{
    containerClass:'nestable',
    fixedItemClass:false,
    draggableItemClass:'item',
    handleClass:'handle',
    regulateMouseOver:false,
    mirrorMaxHeight:100,
    mirrorMaxWidth:300,
    revert:false,
    clone:false
});
lmdd.init(document.getElementById('markup-example'),{
    containerClass:'nestable',
    fixedItemClass:false,
    draggableItemClass:'item',
    handleClass:false,
    regulateMouseOver:false,
    mirrorMaxHeight:100,
    mirrorMaxWidth:300,
    revert:false,
    clone:false
});